name: Build Pipeline
on: [ push, pull_request ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Release
        uses: sanjP10/release-action@1.0.0
        id: validate-release
        with:
          changelog-file-location: ./CHANGELOG.md

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
          ignore: DL3008 DL3009 DL3015 DL3059
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2086
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - run: pip install cfn-lint
      - run: pip install pylint
      - run: cfn-lint fixtures/cloudformation/*
      - run: pylint src/ tests/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - run: pip install coverage
      - run: coverage run -m unittest discover
      - run: coverage report --fail-under 90

  create:
    runs-on: ubuntu-latest
    needs:
      - validate
      - lint
      - test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Release
        uses: sanjP10/release-action@1.0.0
        id: create-release
        with:
          changelog-file-location: ./CHANGELOG.md
          operation: create
